FROM node:20-alpine

WORKDIR /app

# Copy package.json and package-lock.json first (to optimize Docker caching)
COPY package*.json ./

# Install dependencies, including Luxon if it's listed in package.json
RUN npm install

# Install ffmpeg
RUN apk add --no-cache ffmpeg

COPY . .

CMD ["node", "index.js"]
